### ISSUE TITLE
composer shortcuts broken

### ISSUE THREAD

**Issue by martyalicante** [frissdiegurke/nodebb-plugin-shortcuts#4]
it doesn't open composer, also some others doesn't work
will need update

**Comment by frissdiegurke** [comment]
```
  "nbbpm": {
    "compatibility": "^0.6.0"
  }
```
says everything :D

Update is planned. No estimations thought.

**Comment by frissdiegurke** [comment]
Updated (completely reworked).

NodeBB comptibility: `~0.9.0` (at least not tested with `<0.9.0`, may work anyways)
Themes supported: lavender, persona
Composer supported: composer-default
